mqttUser: admin
mqttPassword: 12345678
serverUri: ssl://localhost:8883
caFilePath: MqttCoreTemp/src/main/resources/ca.crt
keyStorePath: MqttCoreTemp/src/main/resources/keystore.jks
keyStorePassword: asdasd
clientId: Core